//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steam_BPM_Customizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Steam_BPM_Customizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _48ico {
            get {
                object obj = ResourceManager.GetObject("_48ico", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://stat.fil.guru/statistics.
        /// </summary>
        internal static string ANONIMOUS_STATISTICS_URL {
            get {
                return ResourceManager.GetString("ANONIMOUS_STATISTICS_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ___ ___ __  __  ___        _             _            
        ///| _ ) _ \  \/  |/ __|  _ __| |_ ___ _ __ (_)______ _ _ 
        ///| _ \  _/ |\/| | (_| || (_-&lt;  _/ _ \ &apos;  \| |_ / -_) &apos;_|
        ///|___/_| |_|  |_|\___\_,_/__/\__\___/_|_|_|_/__\___|_|
        ///
        ///by Alexey D. Filimonov aka &apos;FilimoniC&apos; &lt;alexey@filimonic.net&gt;
        ///
        ///.
        /// </summary>
        internal static string APPLICATION_LOGO {
            get {
                return ResourceManager.GetString("APPLICATION_LOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance of application is running already.
        /// </summary>
        internal static string ERROR_ANOTHER_INSTANCE_ALREADY_RUNNING {
            get {
                return ResourceManager.GetString("ERROR_ANOTHER_INSTANCE_ALREADY_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding file to watch while trying to check R\W functions: {0} : {1}.
        /// </summary>
        internal static string ERROR_FILE_ADDING_TO_WATCH_IOERROR {
            get {
                return ResourceManager.GetString("ERROR_FILE_ADDING_TO_WATCH_IOERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding file to watch: file does not exist or inaccessible: {0}.
        /// </summary>
        internal static string ERROR_FILE_ADDING_TO_WATCH_NOTEXIST {
            get {
                return ResourceManager.GetString("ERROR_FILE_ADDING_TO_WATCH_NOTEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error rewriting file data: {0} : {1}.
        /// </summary>
        internal static string ERROR_FILE_WRITE_FAILURE {
            get {
                return ResourceManager.GetString("ERROR_FILE_WRITE_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening Steam registry key.
        /// </summary>
        internal static string ERROR_REGISTRY_OPEN_STEAM_REGISTY_KEY {
            get {
                return ResourceManager.GetString("ERROR_REGISTRY_OPEN_STEAM_REGISTY_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting Steam path.
        /// </summary>
        internal static string ERROR_REGISTRY_READ_STEAM_PATH {
            get {
                return ResourceManager.GetString("ERROR_REGISTRY_READ_STEAM_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Steam BPM Window detected unknown event {0}.
        /// </summary>
        internal static string ERROR_STEAM_WINDOW_DETECTED_UNKNOWN_STATE {
            get {
                return ResourceManager.GetString("ERROR_STEAM_WINDOW_DETECTED_UNKNOWN_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Could not process XML data :{0}.
        /// </summary>
        internal static string ERROR_TRANSFORMER_ALL_ERROR_XML {
            get {
                return ResourceManager.GetString("ERROR_TRANSFORMER_ALL_ERROR_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Unable to save file {0} : {1}.
        /// </summary>
        internal static string ERROR_TRANSFORMER_MAINMENU_UNABLE_TO_SAVE_FILE {
            get {
                return ResourceManager.GetString("ERROR_TRANSFORMER_MAINMENU_UNABLE_TO_SAVE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to check if application already running : {0}.
        /// </summary>
        internal static string ERROR_UNABLE_TO_DETECT_SINGLE_PROCESS_CHECK {
            get {
                return ResourceManager.GetString("ERROR_UNABLE_TO_DETECT_SINGLE_PROCESS_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FILE_BPMT_ShoppingCartIcon {
            get {
                object obj = ResourceManager.GetObject("FILE_BPMT_ShoppingCartIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Note: 
        ///* Main Screen can take only 3 or 4 buttons,
        ///     depending on your screen resolution.
        ///     Other buttons will not be whown, but will be available
        ///     for navigation
        ///* Some items are not shown normally
        ///     (like &apos;Switch to HDMI Input&apos; when you do not have one)
        ///* GoToLibraryOnStart also enables AddUpperStoreMainMenu and NoStoreButtonMainMenu
        ///      VERY VERY EXPERIMENTAL
        ///.
        /// </summary>
        internal static string HELP_CMDLINE_OPTIONS_DESCRIPTION {
            get {
                return ResourceManager.GetString("HELP_CMDLINE_OPTIONS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---
        ///Example:
        ///   SBPMCustomizer.exe NoProfileIcon AddQuitEntryMainMenu NoUpperExitMainMenu.
        /// </summary>
        internal static string HELP_CMDLINE_OPTIONS_FOOTER {
            get {
                return ResourceManager.GetString("HELP_CMDLINE_OPTIONS_FOOTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Steam BPM customizer
        ///          by Alexey D. &apos;Filimonic&apos; Filimonov &lt;alexey@filimonic.net&gt;
        ///
        ///Usage:   SBPMCustomizer.exe [option [option ...]]
        ///Options:
        ///.
        /// </summary>
        internal static string HELP_HEADER {
            get {
                return ResourceManager.GetString("HELP_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     {0} - {1}.
        /// </summary>
        internal static string HELP_PARAMETER {
            get {
                return ResourceManager.GetString("HELP_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Exit Steam button to Main Screen (labeled EXIT).
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_AddQuitEntryMainMenu {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_AddQuitEntryMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Restart button to Main Screen.
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_AddRestartEntryMainMenu {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_AddRestartEntryMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Shutdown button to Main Screen.
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_AddShutdownEntryMainMenu {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_AddShutdownEntryMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sleep button to Main Screen.
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_AddSleepEntryMainMenu {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_AddSleepEntryMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add small Store top right on Main Screen.
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_AddUpperStoreMainMenu {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_AddUpperStoreMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (PRESET) FMode. Preset by developer. See log.
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_FMode {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_FMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (!!VERY EXPERIMENTAL) Go to Library on start..
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_GoToLibraryOnStart {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_GoToLibraryOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide console window.
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_HideConsole {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_HideConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable BETA button in main menu.
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_NoBetaButtonMainMenu {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_NoBetaButtonMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (!!UNFINISHED) Disable any links that open browser.
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_NoBrowserNavigation {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_NoBrowserNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Change User in Quit menu.
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_NoChangeUser {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_NoChangeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description.
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_NODESCRIPTION {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_NODESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Exit BPM in Quit menu (returns to non-BPM client).
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_NoExitBPM {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_NoExitBPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Exit Steam in Quit menu (this closes Steam client).
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_NoExitSteam {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_NoExitSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Switch to HDMI Input in Quit menu.
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_NoHdmiInput {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_NoHdmiInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables Go Offline in Quit menu.
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_NoOffline {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_NoOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables Go Online in Quit menu and Main Screen.
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_NoOnline {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_NoOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables Parental Lock button in Main Screen.
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_NoParentalLockButtonMainMenu {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_NoParentalLockButtonMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables Profile Icon and &lt;YourNick&gt; button in Main Screen.
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_NoProfileIcon {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_NoProfileIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables Restart in Quit menu.
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_NoRestart {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_NoRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables Settings in Quit menu.
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_NoSettingsMainMenu {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_NoSettingsMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables Settings icon in Main Screen.
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_NoSettingsQuitMenu {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_NoSettingsQuitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables Shutdown in Quit menu.
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_NoShutdown {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_NoShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables Sleep in Quit menu.
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_NoSleep {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_NoSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (!!EXPERIMENTAL) Remove Store button from Main Scr.
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_NoStoreButtonMainMenu {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_NoStoreButtonMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables Turn Off Controller in Quit menu.
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_NoTurnOffCont {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_NoTurnOffCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables Quit icon on Main Screen.
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_NoUpperExitMainMenu {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_NoUpperExitMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables Zero Tracker in Quit menu.
        /// </summary>
        internal static string HELP_PARAMETER_DESCRIPTION_NoZT {
            get {
                return ResourceManager.GetString("HELP_PARAMETER_DESCRIPTION_NoZT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying transformation to file {0}.
        /// </summary>
        internal static string REPORT_APPLYING_TRANSFORMATION {
            get {
                return ResourceManager.GetString("REPORT_APPLYING_TRANSFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command line parameter accepted: {0}.
        /// </summary>
        internal static string REPORT_CMDLINE_PARAMETER_ACCEPTED {
            get {
                return ResourceManager.GetString("REPORT_CMDLINE_PARAMETER_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command line parameter is unsupported: {0}.
        /// </summary>
        internal static string REPORT_CMDLINE_PARAMETER_UNKNOWN {
            get {
                return ResourceManager.GetString("REPORT_CMDLINE_PARAMETER_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File added to watch {0}.
        /// </summary>
        internal static string REPORT_FILE_ADDED_TO_WATCH {
            get {
                return ResourceManager.GetString("REPORT_FILE_ADDED_TO_WATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File change detected: {0} : {1}.
        /// </summary>
        internal static string REPORT_FILE_DETECTED_CHANGED {
            get {
                return ResourceManager.GetString("REPORT_FILE_DETECTED_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIle rename detected: {0} -&gt;{1}.
        /// </summary>
        internal static string REPORT_FILE_DETECTED_RENAMED {
            get {
                return ResourceManager.GetString("REPORT_FILE_DETECTED_RENAMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not watched {0}.
        /// </summary>
        internal static string REPORT_FILE_IS_NOT_WATCHED {
            get {
                return ResourceManager.GetString("REPORT_FILE_IS_NOT_WATCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginnig rewriting file {0}.
        /// </summary>
        internal static string REPORT_FILE_REWRITE_BEGIN {
            get {
                return ResourceManager.GetString("REPORT_FILE_REWRITE_BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File updated {0}.
        /// </summary>
        internal static string REPORT_FILE_UPDATED {
            get {
                return ResourceManager.GetString("REPORT_FILE_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating file original data : {0}.
        /// </summary>
        internal static string REPORT_FILE_UPDATING_ORIGINAL_DATA {
            get {
                return ResourceManager.GetString("REPORT_FILE_UPDATING_ORIGINAL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting modified file state : {0}.
        /// </summary>
        internal static string REPORT_FILE_WRITE_MODIFIED_STATE {
            get {
                return ResourceManager.GetString("REPORT_FILE_WRITE_MODIFIED_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting original file state : {0}.
        /// </summary>
        internal static string REPORT_FILE_WRITE_ORIGINAL_STATE {
            get {
                return ResourceManager.GetString("REPORT_FILE_WRITE_ORIGINAL_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing file data ( {0} bytes ).
        /// </summary>
        internal static string REPORT_FILE_WRTE_DATA {
            get {
                return ResourceManager.GetString("REPORT_FILE_WRTE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File data rewritten : {0}.
        /// </summary>
        internal static string REPORT_FILE_WRTE_DATA_COMPLETE {
            get {
                return ResourceManager.GetString("REPORT_FILE_WRTE_DATA_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locking file {0}.
        /// </summary>
        internal static string REPORT_LOCK_FILE {
            get {
                return ResourceManager.GetString("REPORT_LOCK_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring file watcher....
        /// </summary>
        internal static string REPORT_RESTORE_FILE_WATCHER {
            get {
                return ResourceManager.GetString("REPORT_RESTORE_FILE_WATCHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam path is {0}.
        /// </summary>
        internal static string REPORT_STEAM_PATH {
            get {
                return ResourceManager.GetString("REPORT_STEAM_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam BPM Window creation detected.
        /// </summary>
        internal static string REPORT_STEAM_WINDOW_DETECTED_CREATED {
            get {
                return ResourceManager.GetString("REPORT_STEAM_WINDOW_DETECTED_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam BPM Window destruction detected.
        /// </summary>
        internal static string REPORT_STEAM_WINDOW_DETECTED_DESTROYED {
            get {
                return ResourceManager.GetString("REPORT_STEAM_WINDOW_DETECTED_DESTROYED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File watcher stopping....
        /// </summary>
        internal static string REPORT_STOP_FILE_WATCHER {
            get {
                return ResourceManager.GetString("REPORT_STOP_FILE_WATCHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transforming data....
        /// </summary>
        internal static string REPORT_TRANSFORMER_ALL_TRANSFORMING_BEGIN {
            get {
                return ResourceManager.GetString("REPORT_TRANSFORMER_ALL_TRANSFORMING_BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data transformed.
        /// </summary>
        internal static string REPORT_TRANSFORMER_ALL_TRANSFORMING_END {
            get {
                return ResourceManager.GetString("REPORT_TRANSFORMER_ALL_TRANSFORMING_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process setting {0}.
        /// </summary>
        internal static string REPORT_TRANSFORMER_ALL_UNABLE_TO_PROCESS_SETTING {
            get {
                return ResourceManager.GetString("REPORT_TRANSFORMER_ALL_UNABLE_TO_PROCESS_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPMT_MainMenu ::.
        /// </summary>
        internal static string REPORT_TRANSFORMER_MAINMENU_LOGPREFIX {
            get {
                return ResourceManager.GetString("REPORT_TRANSFORMER_MAINMENU_LOGPREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node disabled : {0}.
        /// </summary>
        internal static string REPORT_TRANSFORMER_MAINMENU_NODE_DISABLED {
            get {
                return ResourceManager.GetString("REPORT_TRANSFORMER_MAINMENU_NODE_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPMT_QuitEntries ::.
        /// </summary>
        internal static string REPORT_TRANSFORMER_QUITENTRIES_LOGPREFIX {
            get {
                return ResourceManager.GetString("REPORT_TRANSFORMER_QUITENTRIES_LOGPREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit menu item disabled: {0}.
        /// </summary>
        internal static string REPORT_TRANSFORMER_QUITENTRIES_NODE_DISABLED {
            get {
                return ResourceManager.GetString("REPORT_TRANSFORMER_QUITENTRIES_NODE_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All watched files updated.
        /// </summary>
        internal static string REPORT_UPDATEALL_FINISHED {
            get {
                return ResourceManager.GetString("REPORT_UPDATEALL_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating all watched files....
        /// </summary>
        internal static string REPORT_UPDATEALL_STARTED {
            get {
                return ResourceManager.GetString("REPORT_UPDATEALL_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watcher started.
        /// </summary>
        internal static string REPORT_WATCHER_STARTED {
            get {
                return ResourceManager.GetString("REPORT_WATCHER_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tenfoot\resource\layout\mainmenu.xml.
        /// </summary>
        internal static string SETTING_FILE_MAINMENU {
            get {
                return ResourceManager.GetString("SETTING_FILE_MAINMENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tenfoot\resource\layout\quitentries.xml.
        /// </summary>
        internal static string SETTING_FILE_QUITENTRIES {
            get {
                return ResourceManager.GetString("SETTING_FILE_QUITENTRIES", resourceCulture);
            }
        }
    }
}
